#!/bin/bash

# Install all the dependencies
sudo apt-get install python3 -y
sudo apt-get install python3-pip -y
sudo apt-get install mysql-server -y
sudo -H pip3 install flask
sudo -H python3 -m pip install mysql-connector
sudo -H pip3 install PyJWT
sudo -H pip3 install requests
sudo apt-get install libssl-dev -y

# Generate a self-signed digital certificate
openssl genrsa -out /etc/ssl/private/server_key.key 4096
sudo mkdir -p /etc/ssl/requests
openssl req -new -key /etc/ssl/private/server_key.key -out /etc/ssl/requests/server_req.csr
openssl x509 -req -days 365 -in /etc/ssl/requests/server_req.csr -signkey /etc/ssl/private/server_key.key -out /etc/ssl/certs/server_cert.crt